/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_adguard_http_parser_HttpMessage */

#ifndef _Included_com_adguard_http_parser_HttpMessage
#define _Included_com_adguard_http_parser_HttpMessage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_adguard_http_parser_HttpMessage
 * Method:    createHttpMessage
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_adguard_http_parser_HttpMessage_createHttpMessage
  (JNIEnv *, jclass);

/*
 * Class:     com_adguard_http_parser_HttpMessage
 * Method:    addHeader
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_adguard_http_parser_HttpMessage_addHeader
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     com_adguard_http_parser_HttpMessage
 * Method:    getHeaders
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_com_adguard_http_parser_HttpMessage_getHeaders
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_adguard_http_parser_HttpMessage
 * Method:    removeHeader
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_adguard_http_parser_HttpMessage_removeHeader
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_adguard_http_parser_HttpMessage
 * Method:    getMethod
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_adguard_http_parser_HttpMessage_getMethod
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_adguard_http_parser_HttpMessage
 * Method:    getUrl
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_adguard_http_parser_HttpMessage_getUrl
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_adguard_http_parser_HttpMessage
 * Method:    setUrl
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_adguard_http_parser_HttpMessage_setUrl
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_adguard_http_parser_HttpMessage
 * Method:    getStatus
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_adguard_http_parser_HttpMessage_getStatus
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_adguard_http_parser_HttpMessage
 * Method:    getStatusCode
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_adguard_http_parser_HttpMessage_getStatusCode
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_adguard_http_parser_HttpMessage
 * Method:    sizeBytes
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_adguard_http_parser_HttpMessage_sizeBytes
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_adguard_http_parser_HttpMessage
 * Method:    getBytes
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_adguard_http_parser_HttpMessage_getBytes__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_adguard_http_parser_HttpMessage
 * Method:    getBytes
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_com_adguard_http_parser_HttpMessage_getBytes__J_3B
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     com_adguard_http_parser_HttpMessage
 * Method:    clone
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_adguard_http_parser_HttpMessage_clone
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_adguard_http_parser_HttpMessage
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_adguard_http_parser_HttpMessage_free
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_adguard_http_parser_HttpMessage
 * Method:    setStatusCode
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_adguard_http_parser_HttpMessage_setStatusCode
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_adguard_http_parser_HttpMessage
 * Method:    setStatus
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_adguard_http_parser_HttpMessage_setStatus
  (JNIEnv *, jclass, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
