/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_adguard_http_parser_NativeParser_Callbacks */

#ifndef _Included_com_adguard_http_parser_NativeParser_Callbacks
#define _Included_com_adguard_http_parser_NativeParser_Callbacks
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
