/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_adguard_http_parser_HttpMessage_HttpHeaderField */

#ifndef _Included_com_adguard_http_parser_HttpMessage_HttpHeaderField
#define _Included_com_adguard_http_parser_HttpMessage_HttpHeaderField
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_adguard_http_parser_HttpMessage_HttpHeaderField
 * Method:    getKey
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_adguard_http_parser_HttpMessage_00024HttpHeaderField_getKey
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_adguard_http_parser_HttpMessage_HttpHeaderField
 * Method:    getValue
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_adguard_http_parser_HttpMessage_00024HttpHeaderField_getValue
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
