/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_adguard_http_parser_NativeLogger */

#ifndef _Included_com_adguard_http_parser_NativeLogger
#define _Included_com_adguard_http_parser_NativeLogger
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_adguard_http_parser_NativeLogger
 * Method:    open0
 * Signature: (ILcom/adguard/http/parser/NativeLogger/NativeCallback;)Lcom/adguard/http/parser/NativeLogger;
 */
JNIEXPORT jobject JNICALL Java_com_adguard_http_parser_NativeLogger_open0
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     com_adguard_http_parser_NativeLogger
 * Method:    open1
 * Signature: (ILjava/lang/String;)Lcom/adguard/http/parser/NativeLogger;
 */
JNIEXPORT jobject JNICALL Java_com_adguard_http_parser_NativeLogger_open1
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_adguard_http_parser_NativeLogger
 * Method:    isOpen
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_adguard_http_parser_NativeLogger_isOpen
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_adguard_http_parser_NativeLogger
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_adguard_http_parser_NativeLogger_close
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_adguard_http_parser_NativeLogger
 * Method:    log
 * Signature: (JILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_adguard_http_parser_NativeLogger_log
  (JNIEnv *, jclass, jlong, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
